### ISSUE TITLE
Compatible with laravel 5.2?

### ISSUE THREAD

**Issue by maesklaas** [devisephp/cms#13]
Hello, 

During install on an existing laravel 5.2 project i run into errors during running "composer update". The error messages give the impression that devisephp is not compatible yet with 5.2. Is this correct? Any idea when it will be compatible?

Thanks in advance!

**Comment by dolbex** [comment]
@maesklaas - we will be working on building compatibility with 5.2 very shortly. I would expect by the end of February we'll be compatible with 5.2

**Comment by maesklaas** [comment]
Thanks for the information! Looking forward to it!

**Comment by dolbex** [comment]
@maesklaas - you should be good to go. Pay careful attention to the upgrade notes at the bottom of the Readme if you're upgrading or grab the updated bootstrap project if you're starting off with a greenfield app.

**Comment by maesklaas** [comment]
Thanks, i will check it out later today.
