### ISSUE TITLE
"tests" folder not installing with the package

### ISSUE THREAD

**Issue by benjaminkohl** [devisephp/cms#16]
I'm trying to install v1.4.1 on a homestead box and I see the "src" and "public" folders in the vendor folder, but the "tests" folder isn't there. This causes an error when I try to dump the autoload or do any artisan commands:

[RuntimeException]                                                                                                           
  Could not scan for classes inside "/home/vagrant/sites/testproject/repo/vendor/devisephp/cms/tests/DeviseTestCase.php" which does not appear to be a file nor a folder  

I thought maybe composer had a bug so I updated it and that didn't fix the issue. I've never had a folder missing from a package before when installing.

**Comment by pistonhonda** [comment]
Appologies, the tests directery was recently added to "export-ignore", but "tests/DeviseTestCase.php" was not removed from "autoload". This is now fixed in 1.4.2.
