### ISSUE TITLE
Workflow local to production

### ISSUE THREAD

**Issue by maesklaas** [devisephp/cms#17]
Hi,

I would like to continue working locally on my pc and from time to time push everything to my production server. For files this is no problem with git. But i have no idea how i can do this for the changes in the database from devise. Do you have a certain methodology? One way to do it would be to go to the local database get all the devise tables en put these in the production database. But then small changes made on production itself would be lost

Thanks

**Comment by dolbex** [comment]
Currently, there is no way to pull this off. When we built Devise we had the idea that we would be building for clients where they could manage their own content (and do) and we could build things locally without risk of contaminating the production environment. 

We realize that this does cause some cumbersome issues if you want to work locally and then 'push' your content changes to your production box. We are working on a solution for this.
