### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by maesklaas** [devisephp/cms#19]
After installing the latest version of Laravel and Devise i get the following error when i start the installation through the browser. It is on the install/environment route as you can see in the error.

After searching on the internet i figured out it has to do with the old method. Some things have to be done with web middleware, but i am not sure how to fix it for devise.

RuntimeException in Request.php line 870:
Session store not set on request.
in Request.php line 870
at Request->session() in Request.php line 545
at Request->old('environment', 'local') in InstallerController.php line 78
at InstallerController->getEnvironment()

**Comment by pistonhonda** [comment]
@maesklaas Apologies, currently Devise does not utilize "middleware groups". That means any required middleware will need to be added to the $middleware property of your App\Http\Kernel. We will work to support the groups, and update our documentation asap.

Example:

`protected $middleware = [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
    ];`

**Comment by maesklaas** [comment]
That solved the issue indeed, thanks!
