### ISSUE TITLE
Creating Permissions

### ISSUE THREAD

**Issue by maesklaas** [devisephp/cms#20]
Hi,

I'm adding a few permissions following the documentation. So i added them in /app/Providers/AppServiceProvider.php in the boot method.

But at this point the facade of RuleManager is not known yet. I get the class not found exception. After some searching i found that the facade is not known at this point. So what is the best way to register these permissions?

Thanks

**Comment by maesklaas** [comment]
Today i found that i had to add a backslash in front of the Facade in order to make it work. But in de meanwhile i came across a permission situation that i do not know how to handle with devise. i have a route like /{parameterslug}/ which comes from a model Parameter. In the AppServiceProvider i do the necessary checks if the user is allowed to see the page for that parameter. I created a parameter_user table to save this. The permission defined in AppServiceProvider needs the slug as input, but now i don't know how to model this in the condition. How do i get the route parameter parameterslug in the condition? It seams like in the examples it always uses a string.

**Comment by pistonhonda** [comment]
Hi maesklaas,

In regards to the RuleManager. Did you add it to the "Class Aliases" list in your app.php?

Make sure you have the following in the 'aliases' array.

'RuleManager'     => Devise\Users\Permissions\RuleManagerFacade::class,

**Comment by pistonhonda** [comment]
Hi maesklass

The default permissions do now allow the checking of route parameters, however you can create a custom "Rule" (http://devisephp.com/docs/permissions/) and use the Route class to get the current route parameters `Route::getCurrentRoute()->parameters()`

**Comment by maesklaas** [comment]
Hi,

The RuleManager alias was already added. Good suggestion as alternative for the parameter. Why didn't i think of that myself.

Thanks!
