### ISSUE TITLE
compatibility with 5.3? 

### ISSUE THREAD

**Issue by barryj** [devisephp/cms#21]
Hi. I have been playing around with the bootstrap version of devisephp (I love it so far), but it downloaded Laravel 2.2

I am   considering integrating the cms version into another project, but this project is running on Laravel 5.3. can you tell me if it is compatible, or if there are plans to upgrade it to 5.3?

Thanks

**Comment by pistonhonda** [comment]
@barryj apologies but we have not tested / integrated with 5.3. We plan up updating for 5.3 soon, and will let you know as soon as it's up.

**Comment by dolbex** [comment]
Check unstable for 5.4 support
