### ISSUE TITLE
Laravel 5.1 fresh install

### ISSUE THREAD

**Issue by moxx** [devisephp/cms#4]
Hi,
installed a fresh  Laravel 5.1 and including devisephp according to documentation ends up in:
```
Fatal error: Declaration of Devise\\Support\\Console\\Command::table() must be compatible with that of Devise\\Support\\IO\\IOInterface::table() in vendor/devisephp/cms/src/Devise/Support/Console/Command.php on line 6
```

**Comment by dolbex** [comment]
Hmm, this is probably a result of Laravel 5.1 which we haven't had a chance to look at yet. We'll start work on this upgrade today. Until then you can change your composer to: 

```
"require": {
		"laravel/framework": "5.0.*",
		"devisephp/cms": "*"
	},
```

**Comment by felixkiss** [comment]
Works for me.

I did:
```
laravel new devise-test
composer require devisephp/cms
```

After that I completed the setup in-browser.

**Comment by dolbex** [comment]
I forgot to close this. 1.2 now supports Laravel 5.1.*
