### ISSUE TITLE
Settings override problem

### ISSUE THREAD

**Issue by Twiebie** [devisephp/cms#6]
Saving the `mail.pretend` setting doesn't work properly as it is saving it as a string instead of a boolean in config.overrides.php

**Comment by dolbex** [comment]
@Twiebie I've raised a ticket for this issue.

**Comment by dolbex** [comment]
@Twiebie - just an update. We have a fix for this in unstable. Should have it in a release tomorrow.

**Comment by Twiebie** [comment]
Thanks for the quick update!

**Comment by dolbex** [comment]
Sorry, was waiting on some other fixes as well. Should be up with 1.2.1
