### ISSUE TITLE
Thoughts on making the users and groups table names configurable?

### ISSUE THREAD

**Issue by tbbuck** [devisephp/cms#8]
Dear lovely DeviseCMS developers,

Is there any reason for relying on tables called "users" and "groups"? (btw not meant to be a nasty or sarcastic question - genuinely interested! :))

I'm currently working on an existing project that would greatly benefit from using Devise, but it already has custom users and groups tables, and using Devise with their existing structure is nasty in the extreme.

Would anyone have any objection to me trying to work out - and hopefully coding - support for making this configurable somehow?

Thanks,
Tom.

**Comment by dolbex** [comment]
Tom,

Thanks for the beautiful letter. ;) 

But seriously - this is definitely something we need to consider. We're talking about it. I'll leave this open. What is your turn time for your current project?

**Comment by tbbuck** [comment]
You're very welcome :)

Turn-around is inside the next couple of weeks - quite quick. For now, I can live with the dirty hack of modifying files and then making sure that devise doesn't get updated.

Off the top of my head - and with zero exploration or testing - I think a pain point might be the migrations files. No idea how well tying configuration values into them might work. Who knows - maybe it's easy and I'm just imagining pitfalls along the way?
