### ISSUE TITLE
Installation in subfolder on domain

### ISSUE THREAD

**Issue by vizo** [devisephp/cms#9]
I added RewriteBase /subfolder in .htaccess as Laravel suggests.

But links are not working in fronend and backend.

Even if i add in template:

``` html
<base href="<?= URL::asset('/') ?>" />
```

base url is correct but links do not work because some urls are absolute and not relative.

**Comment by vizo** [comment]
I replaced all
```html
URL::asset('/
```
with
```html
URL::asset('
```
and i get some progress.

**Comment by dolbex** [comment]
Hey, thanks for all the details. I rose a ticket in our internal ticketing system.
